inmanta/inmanta

.gitignore
CHANGELOG.md
Makefile
inmanta.spec

Add specfile

---

.ci-all.yml
.ci-pyp.yml
.ci-rpm.yml
Makefile

Add .ci files for jenkins

---

.ci-all.yml
.ci-rpm.yml
Makefile

part of #8 
The el8 part was moved to #9

Upload rpms

---

.ci-all.yml
.ci-rpm.yml
Makefile

The cherry-picked commit for the iso4 branch, the contents are the same as #10 
part of #8 
- ~[ ] Attached issue to pull request~
- ~[ ] Changelog entry~

Publish rpms

---

Makefile

updated cloudsmith repo names

---

Makefile

build and publish el8 RPMs
closes #9

build and publish el8 RPMs

---

CHANGELOG.md
inmanta.spec

Set spec file to build far RPMs
Part of inmanta/irt#438

Set spec file to build fat RPMs

---

pyproject.toml

Update pyproject.toml for ISO4.
Part of inmanta/irt#438

Updatep pyproject.toml

---

.ci-build.yml

part of inmanta/irt#441, see inmanta/irt#461
Adds pipeline config for the inmanta-product build pipeline.
I will cherry-pick this on the iso dev branches after merging.

added .ci-build

---

CHANGELOG.md
inmanta.spec

Cherry-pick changes for inmanta/irt#438 from master

Update spec file

---

pyproject.toml

Cherry-picking 05cc7ca166f4ef8e4fead33a38b6fcce151034ff
Part of inmanta/irt#440

Update pyproject.toml (#21)

---

.ci-docs-build.yml

Add .ci file for documentation build.
Part of inmanta/irt#441

Add ci file for docs build

---

.ci-docs-build.yml

Add ci file for docs build.
Part of inmanta/irt#441

Add ci file for docs build (#23)

---

setup.py

Pin version inmanta-core dependency to ~=4.0
Part of inmanta/irt#441

Pin version inmanta-core dependency to ~=4.0

---

setup.py

Pin version inmanta-core dependency to >=4.1.0.dev
Part of inmanta/irt#441

Pin version inmanta-core dependency to >=4.1.0.dev

---

inmanta.spec

Install python packages using --pre when building dev releases.

Install python packages using --pre when building dev releases

---

inmanta.spec

Install python packages using --pre when building dev releases

Install python packages using --pre when building dev releases (#27)

---

setup.py

Set dev version in setup.py

---

inmanta.spec
pyproject.toml

Add dependencies required to build to cryptography package.

Add cryptography dependencies RPM build

---

.ci-check-dependencies.yml
inmanta.spec
pyproject.toml

Add cryptography dependencies for RPM build.

Add cryptography dependencies for RPM build (#41)

---

.github/dependabot.yml
requirements.txt

Update dependabot config

---

.bumpversion.cfg
setup.py

Bump version to 2021.2

---

.bumpversion.cfg
CHANGELOG.md
inmanta.spec
pyproject.toml
setup.py

bump version to 2020.1 and pin internal dependencies.

bump version to 2021.1 and pin internal dependencies

---

.ci-release.yml

Add `.ci` file to perform a release.

Add .ci file to perform a release

---

inmanta.spec

Add dependencies between `inmanta-oss*` RPMs.
closes inmanta/irt#677

Add version constraint to inmanta.spec file

---

changelogs/unreleased/65-web-console.yml

* Short description here *
closes *Add ticket reference here*

fixed change entry schema

---

inmanta.spec

This was merged on the inmanta-core repo in inmanta/inmanta-core#3707. However, the inmanta-core spec file is no longer used. The spec file for OSS is in this repo.
part of #74

enabled UI extension

---

changelogs/unreleased/configure-container-image-tags.yml
pyproject.toml

Add configuration options for container image tags.  
We also now publish the latest tag for any major build we make, as those we will never re-release old versions.

Configure image tags

---

.bumpversion.cfg
pyproject.toml
setup.py

Staged OSS patch release for web-console bugfix.

Stage oss patch release

---

changelogs/unreleased/add-pydantic-v2-build-deps.yml
requirements.setup.txt

Same as inmanta/inmanta-service-orchestrator#444

added build dependencies for pydantic v2
